services:
  uptime:
    image: louislam/uptime-kuma
    container_name: uptime
    restart: always
    volumes:
      - uptime:/app/data
      - /var/run/docker.sock:/app/data/docker.sock

  gammuwrapperuptime:
    container_name: gammuwrapperuptime
    image: ghcr.io/guigui42/gammuwrapper:latest
    restart: always
    environment:
      GAMMUSENDTIMEOUTSECONDS: "45"
    devices:
      - '/dev/serial/by-id/usb-ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ_HUAWEI_Mobile-if00-port0:/dev/ttyUSB1'
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://127.0.0.1:8083/health"]
      interval: 30s
      timeout: 3s
      retries: 3

volumes:
  uptime:
    name: uptime
